markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "@Kimmunmu"
markdown: rdiscount

author: "wayne"
atom-baseurl: "http://kimmunmu.cn"
disqus: "gopherwood"

navigations:
  - title: 内容
    class: fa fa-list-ul
    href: /archive.html
  - title: 标签
    class: fa fa-tags
    href: /tags.html
  - title: 关于我
    class: fa fa-user
    href: /about.html
  - title: 画廊
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: 订阅
    class: fa fa-rss
    href: /atom.xml

